<?php

$variable = array(
//    "/index-old/"              => "/",
//    "/core/views"              => "/",
//    "/node_modules/.env"       => "/",
//    "/node_modules"            => "/",    
//    "/old/(:uri+)/"            => "/",
//    "/furia/(:uri+)/"          => "/",
//    "/fulia/"                  => "/",
//    "/fulia/index.php"         => "/",
//    "/google9a3a1fb0a47d86dd/" => "/",
//    "/vagrant.md"              => "/",
//    "/views/frm-feedback.php"  => "/",
    
    "/blog/2015/10/07/aprenda-a-programar-do-zero.html" => "/blog",
    "/flavio-alexandre-micheletti.php"     => "https://flaviomicheletti.github.io/",
    "/flavio-alexandre-micheletti.html"    => "https://flaviomicheletti.github.io/",
    "/tcc-flavio-alexandre-micheletti.pdf" => "https://flaviomicheletti.github.io/tcc-flavio-alexandre-micheletti.pdf",
    "/schemas/sitemap0-9.xml"              => "/sitemap.xml",
    "/schemas/sitemap.xml"                 => "/sitemap.xml",
    "schemas/sitemap.xml"                  => "/sitemap.xml",
    "/schemas/"                            => "/sitemap.xml",
    "/schemas"                             => "/sitemap.xml",
    "/mapa-do-site/"                       => "/sitemap.xml",
    "/privilegiometro"                     => "http://privilegiometro.devfuria.com.br/",
    "/privilegiometro/"                    => "http://privilegiometro.devfuria.com.br/",
    
    "/js"                => "/javascript/",
    "/js/index.php"      => "/javascript/",
    "/js/(:?curso)/"     => "/javascript/",
    "/js/imagens/"       => "/javascript/",
    "/javascript/forms/" => "/javascript/",
    "/javascript/refs/"  => "/javascript/",
    "/javascript/refatoracao-codigo-limpo/index.html" => "/javascript/",    
    "/javascript/refatoracao-codigo-limpo/"           => "/javascript/",
    "/javascript/node.js/ns-02-baby-steps/"   => "/javascript/node.js/nodejs-02-baby-steps/",
    "/javascript/node.js/ns-03-my-first-io/"  => "/javascript/node.js/nodejs-03-my-first-io/",
    "/javascript/preparando-o-terreno"        => "/javascript/iniciando-com-javascript/",
    "/javascript/numeros-randomicos/"         => "/javascript/numeros-aleatorios/",
    "/javascript/backbone-hello-world/"       => "/javascript/backbone-introducao/",
    "/javascript/backbone-hello-world/"       => "/javascript/backbone-introducao/",
    "/javascript/dom-getelementbyname/"       => "/javascript/dom-getelementsbyname/",
    "/javascript/dom-getelementbyclassname/"  => "/javascript/dom-getelementsbyclassname/",
    "/javascript/mocha-teste-seu-javascript/" => "/javascript/node.js/mocha-teste-seu-javascript/",
    "/javascript/mocha-teste-seu-javascript/" => "/javascript/node.js/mocha-teste-seu-javascript/",
    "/javascript/refs/onclick/"               => "/javascript/",
    "/javascript/refs/queryselectorall/"      => "/javascript/dom-queryselectorall/",
    "/javascript/refs/getelementbytagname/"   => "/javascript/dom-getelementsbytagname/",
    "/javascript/refs/getelementbyname/"      => "/javascript/dom-getelementsbyname/",
    "/javascript/refs/getelementbyid/"        => "/javascript/dom-getelementbyid/",
    "/javascript/refs/dom-add/"               => "/javascript/dom-append-child/",
    "/javascript/refs/dom-create-element/"    => "/javascript/dom-create-element/",
    "/javascript/refs/dom-remove/"            => "/javascript/dom-remove-child/",
    "/js/canvas/?"                                  => "/javascript/canvas/",
    "/js/canvas/aprendendo-canvas-introducao/"      => "/javascript/canvas/introducao/",
    "/js/canvas/lineTo-moveTo/"                     => "/javascript/canvas/lineto-moveto/",
    "/js/canvas/line-width/"                        => "/javascript/canvas/line-width/",
    "/js/canvas/rect-strokeRect-fillRect/"          => "/javascript/canvas/rect-strokerect-fillrect/",
    "/js/canvas/canvas-linhas-rando-coloridas/"     => "/javascript/canvas/col-linhas-rando/",
    "/js/canvas/paths/"                             => "/javascript/canvas/paths/",
    "/js/canvas/canvas-grid/"                       => "/javascript/canvas/col-linhas-grade/",
    "/js/window-object/"                            => "/javascript/refs/objeto-global/",
    "/js/window-object-global/"                     => "/javascript/refs/objeto-global/",
    "/js/math-random-numero-randomico-em-javascript/"           => "/javascript/numeros-aleatorios/",
    "/js/math-random-numero-randomico-em-javascript/index.php"  => "/javascript/numeros-aleatorios/",
    "/js/basico/"                           => "/javascript/",
    "/js/basico/draft/"                     => "/javascript/",
    "/js/basico/intro/"                     => "/javascript/iniciando-com-javascript/",
    "/js/basico/intro/index.php"            => "/javascript/iniciando-com-javascript/",
    "/js/basico/intro/materia.mrk"          => "/javascript/iniciando-com-javascript/",
    "/js/basico/code-lampadas/"             => "/javascript/code-lampada/",
    "/js/basico/code-lampadas-refatorando/" => "/javascript/code-lampada/",
    "/js/basico/debugando/"                 => "/javascript/debugando/",
    "/js/basico/input-radio-button/"        => "/javascript/forms/input-radio-button/",
    "/js/basico/select-combobox/"           => "/javascript/forms/select-combobox/",
    "/js/basico/input-radio-button/"        => "/javascript/forms/input-radio-button/",
    "/js/basico/(:uri+)/"                   => "/javascript/",
    
    "/html-css/formularios/intro-formularios-web/"      => "/html-css/introducao-formularios-web/",
    "/html-css/formularios-web/"                        => "/html-css/introducao-formularios-web/",
    "/html-css/basico/formularios-web/?"                => "/html-css/introducao-formularios-web/",
    "/html-css/historia-html/?"                         => "/html-css/introducao-html/",
    "/html-css/basico/html-e-css-intro/p_img_d.html"    => "/html-css/",
    "/html-css/imagens/"                                => "/html-css/",
    "/html-css/basico/?"                                => "/html-css/",
    "/html-css/basico/index.php"                        => "/html-css/",
    "/html-css/basico/reset-css/"                       => "/html-css/",
    "/html-css/basico/validando-html-e-css/code1.html"  => "/html-css/",
    "/html-css/basico/validando-html-e-css/materia.mrk" => "/html-css/",    
    "/html-css/basico/intro/?"                          => "/html-css/introducao-html/",
    "/html-css/basico/html-intro/?"                     => "/html-css/introducao-html/",
    "/html-css/basico/html-e-css-intro/"                => "/html-css/",
    "/html-css/basico/semantica/?"                      => "/html-css/introducao-html/",
    "/html-css/basico/onde-tudo-comecou/(.*)?"          => "/html-css/introducao-html/",
    "/html-css/basico/primeiro-html/"                   => "/html-css/primeiro-html/",
    "/html-css/basico/css-intro/"                       => "/html-css/introducao-css/",
    "/html-css/basico/elementos-inline-block-level/"    => "/html-css/elementos-inline-block-level/",
    "/html-css/basico/primeiro-html/slide-primeiro-html.odp"  => "/html-css/primeiro-html/",
    "/html-css/basico/primeiro-html"                    => "/html-css/primeiro-html/",
    "/html-css/basico/primeiro-html/materia.md"         => "/html-css/primeiro-html/",
    "/%3Cb%3Ehtml%3C/b%3E-css/formularios/combo%3Cb%3Ebox%3C/b%3E" => "/html-css/formularios/combobox/",
    
    "/logica/?"                                     => "/logica-de-programacao/",    
    "/logica/basico/(:uri+)/"                       => "/logica-de-programacao/",    
    "/logica-de-programacao/basico/(:uri+)/"        => "/logica-de-programacao/",    
    "/logica-de-programacao/o-que-e-tdd"            => "/tdd/",
    "/logica-de-programacao/o-que-e-tdd/"           => "/tdd/",
    "/logica-de-programacao/entendendo-o-assert-c/" => "/c/rodando-os-testes/",
    
    "/logica-de-programacao/eleitores/"                 => "/logica-de-programacao/votos-em-relacao-ao-total-de-eleitores/",
    "/logica-de-programacao/c-eleitores/"               => "/logica-de-programacao/votos-em-relacao-ao-total-de-eleitores/",
    "/logica-de-programacao/custo-carro/"               => "/logica-de-programacao/custo-de-fabricacao-de-um-carro/",
    "/logica-de-programacao/c-custo-carro/"             => "/logica-de-programacao/custo-de-fabricacao-de-um-carro/",
    "/logica-de-programacao/dias-n-meses/"              => "/logica-de-programacao/descobrir-os-dias-de-n-meses/",
    "/logica-de-programacao/c-dias-n-meses/"            => "/logica-de-programacao/",   
    "/logica-de-programacao/antecessor-sucessor/"       => "/logica-de-programacao/antecessor-e-sucessor-de-um-numero-qualquer/",
    "/logica-de-programacao/media-simples/"             => "/logica-de-programacao/media-simples-de-3-numeros/",
    "/logica-de-programacao/c-duas-variaveis/"          => "/logica-de-programacao/trocar-o-valor-de-duas-variaveis/",
    "/logica-de-programacao/duas-variaveis/"            => "/logica-de-programacao/trocar-o-valor-de-duas-variaveis/",
    "/logica-de-programacao/duas-variaveis-ponteiros/"  => "/logica-de-programacao/trocar-o-valor-de-duas-variaveis-utilizando-ponteiros/",
    "/logica-de-programacao/dobro/?"                    => "/logica-de-programacao/o-dobro-de-um-numero-qualquer/",
    "/logica-de-programacao/dobro-func/?"               => "/logica-de-programacao/o-dobro-de-um-numero-qualquer/",
    "/logica-de-programacao/c-dobro-func/"              => "/logica-de-programacao/o-dobro-de-um-numero-qualquer/",
    "/logica-de-programacao/c-dobro/"                   => "/logica-de-programacao/o-dobro-de-um-numero-qualquer/",
    "/logica-de-programacao/c-celsius-fahrenheit/"      => "/logica-de-programacao/celsius-fahrenheit/",
    "/logica-de-programacao/c-equacao-2grau/"           => "/logica-de-programacao/equacao-2grau/",
    "/logica-de-programacao/c-juros-simples/"           => "/logica-de-programacao/juros-simples/",
    "/logica-de-programacao/c-media-simples/"           => "/logica-de-programacao/media-simples/",
    "/logica-de-programacao/c-maior-que-dez/"           => "/logica-de-programacao/maior-que-dez/",
    "/logica-de-programacao/c-mmc/"                     => "/logica-de-programacao/mmc/",
    "/logica-de-programacao/c-mdc/"                     => "/logica-de-programacao/mdc/",
    "/logica-de-programacao/c-par-impar/"               => "/logica-de-programacao/par-impar/",
    "/logica-de-programacao/c-positivo/"                => "/logica-de-programacao/positivo/",
    "/logica-de-programacao/c-primo/"                   => "/logica-de-programacao/primo/",
    "/logica-de-programacao/c-operacoes-mat/"           => "/logica-de-programacao/operacoes-mat/",
    "/logica-de-programacao/salario-reajuste/"          => "/logica-de-programacao/reajustando-o-salario/",
    "/logica-de-programacao/c-salario-reajuste/"        => "/logica-de-programacao/reajustando-o-salario/",
    "/logica-de-programacao/c-soma-digitos/"            => "/logica-de-programacao/soma-digitos/",
    "/logica-de-programacao/c-strings-comparar/"        => "/logica-de-programacao/strings-comparar/",
    "/logica-de-programacao/c-strings-contar/"          => "/logica-de-programacao/strings-contar/",
    "/logica-de-programacao/c-strings-concatenar/"      => "/logica-de-programacao/strings-concatenar/",
    "/logica-de-programacao/c-strings-contar-vogais/"   => "/logica-de-programacao/strings-contar-vogais/",
    "/logica-de-programacao/c-strings-reverse/"         => "/logica-de-programacao/strings-reverse/",
    "/logica-de-programacao/c-vetor-simples/"           => "/logica-de-programacao/vetor-simples/",
    "/logica-de-programacao/c-vetor-copia/"             => "/logica-de-programacao/vetor-copia/",
    "/logica-de-programacao/c-vetor-maior-menor-indice/"=> "/logica-de-programacao/vetor-maior-menor-indice/",
    "/logica-de-programacao/c-vetor-soma/"              => "/logica-de-programacao/vetor-soma/",
    "/logica-de-programacao/c-vetor-valores-repetidos/" => "/logica-de-programacao/vetor-valores-repetidos/",
    "/logica-de-programacao/c-positivo/"                => "/logica-de-programacao/positivo/",
    "/logica-de-programacao/c-vetor-valores-repetidos/" => "/logica-de-programacao/vetor-valores-repetidos/",
    "/logica-de-programacao/calc-dobro/"                => "/logica-de-programacao/dobro-func/",
    "/logica-de-programacao/cpp-area-quadra-cubo/"      => "/logica-de-programacao/area-quadra-cubo/",
    "/logica-de-programacao/cpp-calc-dobro/"            => "/logica-de-programacao/dobro-oop/",
    "/logica-de-programacao/cpp-antecessor-sucessor/"   => "/logica-de-programacao/antecessor-sucessor/",
    "/logica-de-programacao/cpp-calc-dobro/"            => "/logica-de-programacao/calc-dobro/",
    "/logica-de-programacao/cpp-triangulo/"             => "/logica-de-programacao/calc-dobro/",
    "/logica-de-programacao/exemplos"                   => "/logica-de-programacao/",
    "/logica-de-programacao/exemplos-na-linguagem"      => "/logica-de-programacao/",
    "/logica-de-programacao/introducao-linguagem-c"     => "/c/",
    "/logica-de-programacao/introducao-linguagem-c/"    => "/c/",
    "/logica-de-programacao/c-antecessor-sucessor/"     => "/logica-de-programacao/antecessor-sucessor/",

    "/misc/cgi-common-gateway-interface/&amp;sa=U&amp;ved=0ahUKEwj9u5bH1v7KAhUI8j4KHQbdCnM4UBAWCD0wDw&amp;usg=AFQjCNFyC8eqH68VR_5sxUleU5NEh4ltNQ" => "/misc/cgi-common-gateway-interface/",
    "/misc/cgi-common-gateway-interface/&amp;sa=U&amp;ved=0ahUKEwjLx7Xo1ubKAhVCxxoKHT3LCqs4UBAWCD0wDw&amp;usg=AFQjCNFyC8eqH68VR_5sxUleU5NEh4ltNQ" => "/misc/cgi-common-gateway-interface/",

    "/mysql/"                                   => "/sql/",
    "/mysql-sql"                                => "/sql/",
    "/mysql-sql/"                               => "/sql/",
    "/mysql-sql/?"                              => "/sql/",
    "/mysql-sql/intro/"                         => "/sql/",    
    "/mysql/basico/?"                           => "/sql/",
    "/mysql/basico/intro/?"                     => "/sql/",
    "/mysql-sql/basico/criando-base-tabela/"    => "/sql/",
    "/mysql-sql/basico/primeiros-passos-mysql/" => "/sql/",
    "/sql/mysql-erro-1064/"                     => "/sql/mysql-ler-mensagens-erro/",
    
    "/php/refs/"                                => "/php",
    "/php/forms/"                               => "/php",
    "/php/basico/"                              => "/php",
    "/php/basico/arrays-vetores-matrizes/"      => "/php/criando-iterando-um-array/",
    "/php/basico/boas-praticas/"                => "/php/phptherightway/",
    "/php/basico/pe-na-jaca"                    => "/php/phptherightway/",
    "/php/basico/pe-na-jaca/"                   => "/php/phptherightway/",
    "/php/basico/antes-de-enfiar-o-pe-na-jaca/" => "/php/phptherightway/",
    "/php/basico/debugando/"                    => "/php/debugando/",
    "/php/basico/debugando/materia.md"          => "/php/debugando/",
    "/php/basico/checkbox-checked/"             => "/php/forms/checkbox/",
    "/php/basico/textbox-password-textarea/"    => "/php/forms/textbox-password-textarea/",
    "/php/basico/select-multiple/"              => "/php/forms/select-multiple/",
    "/php/basico/input-radio-button/"           => "/php/forms/radio-button/",
    "/php/basico/enviando-dados-via-get-post/"  => "/php/forms/enviando-dados-via-get-post/",
    "/php/basico/recebendo-dados-via-get-post/" => "/php/forms/recebendo-dados-via-get-post/",
    "/php/basico/instalando-o-ambiente/"        => "/php/instalando-o-ambiente/",
    "/php/basico/metodo-http-get-post/"         => "/php/forms/enviando-dados-via-get-post/",
    "/php/basico/um-bom-comeco/"                => "/php",
    "/php/basico/combobox-input-form-select/"   => "/php/forms/combobox/",
    "/php/basico/estudos-de-logica-1-ao-5/"     => "/logica-de-programacao/",
    "/php/basico/estudos-de-logica-6-ao-10/"    => "/logica-de-programacao/",
    "/php/nivel-zero/(:uri+)"                   => "/php",
    "/php/basico/logica-de-programacao/"        => "/logica-de-programacao/",
    "/php/forms/checkbox/-"                     => "/php/forms/checkbox/",
    "/php/arrays-vetores-matrizes/"             => "/php/criando-iterando-um-array/",
    "/php/metodo-http-get-post/index.html"      => "/php/como-funcionam-os-metodos-get-e-post/",    
    "/php/metodo-http-get-post/"                => "/php/como-funcionam-os-metodos-get-e-post/",
    "/twig.md"                                  => "/php/twig/",
    
    "/python/django-error"     => "/python/",
    
    "/regexp"                  => "/regex/",
    "/regexp/"                 => "/regex/",
    "/regexp//"                => "/regex/",
    "/regexp/index.php"        => "/regex/",
    "/regexp/?curso"           => "/regex/",
    "/regexp/basico/?(:uri+)"  => "/regex/",
    "/regexp/basico/draft/"    => "/regex/",
    "/regexp/basico/intro/"    => "/regex/",
    "/regex/relacao-completa/" => "/regex/",
	
    "/regexp/basico/pattern-test/"                              => "/javascript/refs/pattern-test/",
    "/regexp/basico/ponto"                                      => "/regex/metacaractere-ponto/",
    "/regexp/basico/ponto/"                                     => "/regex/metacaractere-ponto/",
    "/regexp/basico/string-match"                               => "/javascript/refs/string-match/",
    "/regexp/basico/string-match/"                              => "/javascript/refs/string-match/",
    "/regexp/basico/varios-resultados-match-test-exec/"         => "/javascript/refs/global-g/",
    "/regexp/basico/varios-resultados-preg-match-all/index.php" => "/php/preg-match-all-basico/",

    "/script-para-onde-envio-os-dados.php"                   => "/php/",
    "/seguranca-da-informacao/owasp-topten-2010-introducao/" => "/seguranca-da-informacao/owasp-topten-2010/",

    "/tdd/tdd-test-driven-development/"           => "/logica-de-programacao/tdd-junto-com-logica-assim-tao-cedo/",
    "/tdd/tdd-test-driven-development/index.html" => "/logica-de-programacao/tdd-junto-com-logica-assim-tao-cedo/",
    "/tdd/exemplo-tdd-antecessor-sucessor/"     => "/tdd/",
    "/tdd/exemplo-tdd-area-quadra-oop/"         => "/tdd/",
    "/tdd/exemplo-tdd-area-quadrada/"           => "/tdd/",
    "/tdd/exemplo-tdd-area-quadra/"             => "/tdd/",
    "/tdd/exemplo-tdd-custo-carro/"             => "/tdd/",
    "/tdd/exemplo-tdd-dias-n-meses/"            => "/tdd/",
    "/tdd/exemplo-tdd-duas-variaveis/"          => "/tdd/",
    "/tdd/exemplo-tdd-eleitores/"               => "/tdd/",
    "/tdd/exemplo-tdd-equacao-2grau/"           => "/tdd/",
    "/tdd/exemplo-tdd-maior-que-dez/"           => "/tdd/",
    "/tdd/exemplo-tdd-media-simples/"           => "/tdd/",
    "/tdd/exemplo-tdd-operacoes-mat/"           => "/tdd/",
    "/tdd/exemplo-tdd-positivo/"                => "/tdd/",
    "/tdd/exemplo-tdd-primo/"                   => "/tdd/",
    "/tdd/exemplo-tdd-salario-reajuste/"        => "/tdd/",
    "/tdd/exemplo-tdd-antecessor-sucessor-oop/" => "/tdd/",
    "/tdd/exemplo-tdd-celsius-fahrenheit/"      => "/tdd/",

    "/git/iniciando-com-git/" => "/git/",
    "/git/nao-pedir-senha/"   => "/git/netrc-nao-pedir-senha/",
    
    "/linux/resetar-senha%20de-mysql/"            => "/linux",
    "/entendendo-e-usando-permissoes-no-linux.md" => "/linux",
    "/linux/cookbook/"                            => "/linux/receitas-de-instalacao-de-softwares-no-linux/",
    "/linux/cookbook/recordmydesktop/"            => "/linux/instalando-gtk-recordmydesktop/",
    "/linux/cookbook/recordmydesktop/"            => "/linux/instalando-gtk-recordmydesktop/",
    "/linux/reiniciar-servidor-apache"            => "/linux/apache-como-reiniciar-servidor-apache/",
    "/linux/reiniciar-servidor-apache/"           => "/linux/apache-como-reiniciar-servidor-apache/",
    
    
);

foreach ($variable as $key => $value) {
    App::$slim->get($key, function () use ($value) {
        App::$slim->redirect($value, 301);
    });
}

App::$slim->get('/linux/cookbook/(:uri+)', function ($pag) {
    $nova_url = "/linux/instalando-" . $pag[0] . "/";
    App::$slim->redirect($nova_url, 301);
});

App::$slim->get('/javascript/refs/(:uri+)', function ($pag) {
    $nova_url = "/javascript/" . $pag[0] . "/";
    App::$slim->redirect($nova_url, 301);
});
